### ISSUE TITLE
Add a permalink option

### ISSUE THREAD

**Issue by samueldr** [samueldr/nixos-packages-explorer#5]
https://github.com/NixOS/nixos-homepage/pull/120#issuecomment-377639785

> Also, regex is not something a normal user is able to use. Instead it should not be necessary to use it.

> Let's say I can subtly insert a way to permalink to a particular attribute :sweat_smile:, as this would be a better experience than using a regex. Using such link could also unfold the result row automatically.

**Comment by davidak** [comment]
I think this form would be sane:

link to screen in latest nixos stable (default channel):
https://nixos.org/nixos/packages.html#screen

link to screen in specific nixos channel (the user has selected):
https://nixos.org/nixos/packages.html#nixos-17.09-screen

**Comment by samueldr** [comment]
The permalinks will (by default) be more verbose than expected, but they stash the current state of the application; this way giving a permalink you're giving a snapshot of almost all the state necessary to restart the app as it you were seeing it.

The links *can* be cleaned up and will default to the first channel if no channel is given in the link.

 * https://nix.samueldr.com/explorer/?attr=google-chrome-beta&channel=nixos-17.09&query=%5Egoogle-chrome&unfree=true
 * https://nix.samueldr.com/explorer/?attr=google-chrome-beta&channel=nixos-17.09
 * https://nix.samueldr.com/explorer/?attr=google-chrome-beta

They all work out to the `attr` `google-chrome-beta`, but present a different state when clicked.

 * * *

> Why not use the `#hash fragment` of the URL?

Because there is no standard for how that part works, while the query string is de-facto standardised enough for use.
